'use strict';

module.exports = function (grunt) {

  // Please see the Grunt documentation for more information regarding task
  // creation: http://gruntjs.com/creating-tasks

  grunt.registerMultiTask(
    'dimensional_grunt_icon_import',
    'Imports icon sets (Icomoon) into a project',
    function () {

      function importCss(srcFile, targetFile) {
        var css = grunt.file.read(srcFile);
        var prefix =css.match(/([^]*?)\[class\^="icon-"\]/);
        var less = '/*This file is generated by a Grunt task. */\n\n';
        less += '@icon-fonts: "./icons/fonts";\n\n';
        less += prefix[1];
        var format = css.match(/\[class\^="icon-"\][^{}]+(\{[^}]+\})/);
        less += '.icon() ' + format[1] + "\n";
        less = less.replace(/url\('fonts\//g, 'url(\'@{icon-fonts}/');
        var icons = css.match(/(\.icon-[^:]+):before\s*\{(([^}]+?))\}/g);
        var icon;
        for (var i = 0; i < icons.length; i++) {
          icon = icons[i].match(/(\.icon-[^:]+):before\s*\{\s*(content:.+)/);
          less += icon[1] + " {\n";
          less += "    &:before {\n";
          less += "        .icon;\n";
          less += "        " + icon[2] + "\n";
          less += "    }\n";
          less += "}\n";
          less += icon[1] + "-after() {\n";
          less += "    &:after {\n";
          less += "        .icon;\n";
          less += "        " + icon[2] + "\n";
          less += "    }\n";
          less += "}\n";
        }
        return grunt.file.write(targetFile, less);
      }

      function copyFonts(srcDirectory, targetDirectory) {
        var files, counter = 0;
        files = grunt.file.expand(
          {
            cwd : srcDirectory,
            nonull : true
          },
          ['*.*']
        );
        for (var i = files.length - 1; i >= 0; i--) {
          grunt.verbose.writeln('Copy: ' + srcDirectory + '/' + files[i]);
          grunt.file.copy(srcDirectory + '/' + files[i], targetDirectory + '/' + files[i])
          counter++;
        }
        return counter;
      }

      var options = this.options(
        {
          src : 'resources/icons',
          target : 'src/styles/icons'
        }
      );
      var srcFile = options.src + '/style.css';
      var targetFile = options.target + '/icons.less';
      if (importCss(srcFile, targetFile)) {
        grunt.log.writeln('Import: ' + srcFile);
        grunt.log.writeln('Created: ' + targetFile);
        var fileCount = copyFonts(options.src + '/fonts', options.target + '/fonts');
        grunt.log.writeln('Copied ' + fileCount + ' font files');
      }
    }
  );

};
